/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as V4RouteImport } from './routes/v4'
import { Route as V3RouteImport } from './routes/v3'
import { Route as V2RouteImport } from './routes/v2'
import { Route as V1RouteImport } from './routes/v1'
import { Route as UnderstandingRouteImport } from './routes/understanding'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as MyPlansRouteImport } from './routes/my-plans'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as FindDoctorsRouteImport } from './routes/find-doctors'
import { Route as DeckRouteImport } from './routes/deck'
import { Route as ComparePlansRouteImport } from './routes/compare-plans'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V4IndexRouteImport } from './routes/v4.index'
import { Route as V3IndexRouteImport } from './routes/v3.index'
import { Route as DeckIndexRouteImport } from './routes/deck.index'
import { Route as V4SummaryRouteImport } from './routes/v4.summary'
import { Route as V4PrioritiesRouteImport } from './routes/v4.priorities'
import { Route as V4NextStepRouteImport } from './routes/v4.next-step'
import { Route as V4MatchesRouteImport } from './routes/v4.matches'
import { Route as V4IntakeRouteImport } from './routes/v4.intake'
import { Route as V3SummaryRouteImport } from './routes/v3.summary'
import { Route as V3PrioritiesRouteImport } from './routes/v3.priorities'
import { Route as V3NextStepRouteImport } from './routes/v3.next-step'
import { Route as V3MatchesRouteImport } from './routes/v3.matches'
import { Route as V3IntakeRouteImport } from './routes/v3.intake'
import { Route as DeckLiveRouteImport } from './routes/deck.live'
import { Route as DeckAiRouteImport } from './routes/deck.ai'
import { Route as ApiVoiceSessionRouteImport } from './routes/api/voice-session'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as WorkspaceActivityActivityIdRouteImport } from './routes/workspace.activity.$activityId'
import { Route as ApiV4ChatRouteImport } from './routes/api/v4/chat'
import { Route as ApiV3GeminiLiveTokenRouteImport } from './routes/api/v3/gemini-live-token'
import { Route as ApiV3ChatRouteImport } from './routes/api/v3/chat'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const V4Route = V4RouteImport.update({
  id: '/v4',
  path: '/v4',
  getParentRoute: () => rootRouteImport,
} as any)
const V3Route = V3RouteImport.update({
  id: '/v3',
  path: '/v3',
  getParentRoute: () => rootRouteImport,
} as any)
const V2Route = V2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const V1Route = V1RouteImport.update({
  id: '/v1',
  path: '/v1',
  getParentRoute: () => rootRouteImport,
} as any)
const UnderstandingRoute = UnderstandingRouteImport.update({
  id: '/understanding',
  path: '/understanding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPlansRoute = MyPlansRouteImport.update({
  id: '/my-plans',
  path: '/my-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const FindDoctorsRoute = FindDoctorsRouteImport.update({
  id: '/find-doctors',
  path: '/find-doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckRoute = DeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparePlansRoute = ComparePlansRouteImport.update({
  id: '/compare-plans',
  path: '/compare-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V4IndexRoute = V4IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V4Route,
} as any)
const V3IndexRoute = V3IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V3Route,
} as any)
const DeckIndexRoute = DeckIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeckRoute,
} as any)
const V4SummaryRoute = V4SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => V4Route,
} as any)
const V4PrioritiesRoute = V4PrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => V4Route,
} as any)
const V4NextStepRoute = V4NextStepRouteImport.update({
  id: '/next-step',
  path: '/next-step',
  getParentRoute: () => V4Route,
} as any)
const V4MatchesRoute = V4MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => V4Route,
} as any)
const V4IntakeRoute = V4IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => V4Route,
} as any)
const V3SummaryRoute = V3SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => V3Route,
} as any)
const V3PrioritiesRoute = V3PrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => V3Route,
} as any)
const V3NextStepRoute = V3NextStepRouteImport.update({
  id: '/next-step',
  path: '/next-step',
  getParentRoute: () => V3Route,
} as any)
const V3MatchesRoute = V3MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => V3Route,
} as any)
const V3IntakeRoute = V3IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => V3Route,
} as any)
const DeckLiveRoute = DeckLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => DeckRoute,
} as any)
const DeckAiRoute = DeckAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DeckRoute,
} as any)
const ApiVoiceSessionRoute = ApiVoiceSessionRouteImport.update({
  id: '/api/voice-session',
  path: '/api/voice-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceActivityActivityIdRoute =
  WorkspaceActivityActivityIdRouteImport.update({
    id: '/activity/$activityId',
    path: '/activity/$activityId',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const ApiV4ChatRoute = ApiV4ChatRouteImport.update({
  id: '/api/v4/chat',
  path: '/api/v4/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV3GeminiLiveTokenRoute = ApiV3GeminiLiveTokenRouteImport.update({
  id: '/api/v3/gemini-live-token',
  path: '/api/v3/gemini-live-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV3ChatRoute = ApiV3ChatRouteImport.update({
  id: '/api/v3/chat',
  path: '/api/v3/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/compare-plans': typeof ComparePlansRoute
  '/deck': typeof DeckRouteWithChildren
  '/find-doctors': typeof FindDoctorsRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/my-plans': typeof MyPlansRoute
  '/plans': typeof PlansRoute
  '/understanding': typeof UnderstandingRoute
  '/v1': typeof V1Route
  '/v2': typeof V2Route
  '/v3': typeof V3RouteWithChildren
  '/v4': typeof V4RouteWithChildren
  '/workspace': typeof WorkspaceRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/voice-session': typeof ApiVoiceSessionRoute
  '/deck/ai': typeof DeckAiRoute
  '/deck/live': typeof DeckLiveRoute
  '/v3/intake': typeof V3IntakeRoute
  '/v3/matches': typeof V3MatchesRoute
  '/v3/next-step': typeof V3NextStepRoute
  '/v3/priorities': typeof V3PrioritiesRoute
  '/v3/summary': typeof V3SummaryRoute
  '/v4/intake': typeof V4IntakeRoute
  '/v4/matches': typeof V4MatchesRoute
  '/v4/next-step': typeof V4NextStepRoute
  '/v4/priorities': typeof V4PrioritiesRoute
  '/v4/summary': typeof V4SummaryRoute
  '/deck/': typeof DeckIndexRoute
  '/v3/': typeof V3IndexRoute
  '/v4/': typeof V4IndexRoute
  '/api/v3/chat': typeof ApiV3ChatRoute
  '/api/v3/gemini-live-token': typeof ApiV3GeminiLiveTokenRoute
  '/api/v4/chat': typeof ApiV4ChatRoute
  '/workspace/activity/$activityId': typeof WorkspaceActivityActivityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/compare-plans': typeof ComparePlansRoute
  '/find-doctors': typeof FindDoctorsRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/my-plans': typeof MyPlansRoute
  '/plans': typeof PlansRoute
  '/understanding': typeof UnderstandingRoute
  '/v1': typeof V1Route
  '/v2': typeof V2Route
  '/workspace': typeof WorkspaceRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/voice-session': typeof ApiVoiceSessionRoute
  '/deck/ai': typeof DeckAiRoute
  '/deck/live': typeof DeckLiveRoute
  '/v3/intake': typeof V3IntakeRoute
  '/v3/matches': typeof V3MatchesRoute
  '/v3/next-step': typeof V3NextStepRoute
  '/v3/priorities': typeof V3PrioritiesRoute
  '/v3/summary': typeof V3SummaryRoute
  '/v4/intake': typeof V4IntakeRoute
  '/v4/matches': typeof V4MatchesRoute
  '/v4/next-step': typeof V4NextStepRoute
  '/v4/priorities': typeof V4PrioritiesRoute
  '/v4/summary': typeof V4SummaryRoute
  '/deck': typeof DeckIndexRoute
  '/v3': typeof V3IndexRoute
  '/v4': typeof V4IndexRoute
  '/api/v3/chat': typeof ApiV3ChatRoute
  '/api/v3/gemini-live-token': typeof ApiV3GeminiLiveTokenRoute
  '/api/v4/chat': typeof ApiV4ChatRoute
  '/workspace/activity/$activityId': typeof WorkspaceActivityActivityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/compare-plans': typeof ComparePlansRoute
  '/deck': typeof DeckRouteWithChildren
  '/find-doctors': typeof FindDoctorsRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/my-plans': typeof MyPlansRoute
  '/plans': typeof PlansRoute
  '/understanding': typeof UnderstandingRoute
  '/v1': typeof V1Route
  '/v2': typeof V2Route
  '/v3': typeof V3RouteWithChildren
  '/v4': typeof V4RouteWithChildren
  '/workspace': typeof WorkspaceRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/voice-session': typeof ApiVoiceSessionRoute
  '/deck/ai': typeof DeckAiRoute
  '/deck/live': typeof DeckLiveRoute
  '/v3/intake': typeof V3IntakeRoute
  '/v3/matches': typeof V3MatchesRoute
  '/v3/next-step': typeof V3NextStepRoute
  '/v3/priorities': typeof V3PrioritiesRoute
  '/v3/summary': typeof V3SummaryRoute
  '/v4/intake': typeof V4IntakeRoute
  '/v4/matches': typeof V4MatchesRoute
  '/v4/next-step': typeof V4NextStepRoute
  '/v4/priorities': typeof V4PrioritiesRoute
  '/v4/summary': typeof V4SummaryRoute
  '/deck/': typeof DeckIndexRoute
  '/v3/': typeof V3IndexRoute
  '/v4/': typeof V4IndexRoute
  '/api/v3/chat': typeof ApiV3ChatRoute
  '/api/v3/gemini-live-token': typeof ApiV3GeminiLiveTokenRoute
  '/api/v4/chat': typeof ApiV4ChatRoute
  '/workspace/activity/$activityId': typeof WorkspaceActivityActivityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/compare-plans'
    | '/deck'
    | '/find-doctors'
    | '/learn'
    | '/login'
    | '/my-plans'
    | '/plans'
    | '/understanding'
    | '/v1'
    | '/v2'
    | '/v3'
    | '/v4'
    | '/workspace'
    | '/api/chat'
    | '/api/tts'
    | '/api/voice-session'
    | '/deck/ai'
    | '/deck/live'
    | '/v3/intake'
    | '/v3/matches'
    | '/v3/next-step'
    | '/v3/priorities'
    | '/v3/summary'
    | '/v4/intake'
    | '/v4/matches'
    | '/v4/next-step'
    | '/v4/priorities'
    | '/v4/summary'
    | '/deck/'
    | '/v3/'
    | '/v4/'
    | '/api/v3/chat'
    | '/api/v3/gemini-live-token'
    | '/api/v4/chat'
    | '/workspace/activity/$activityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/compare-plans'
    | '/find-doctors'
    | '/learn'
    | '/login'
    | '/my-plans'
    | '/plans'
    | '/understanding'
    | '/v1'
    | '/v2'
    | '/workspace'
    | '/api/chat'
    | '/api/tts'
    | '/api/voice-session'
    | '/deck/ai'
    | '/deck/live'
    | '/v3/intake'
    | '/v3/matches'
    | '/v3/next-step'
    | '/v3/priorities'
    | '/v3/summary'
    | '/v4/intake'
    | '/v4/matches'
    | '/v4/next-step'
    | '/v4/priorities'
    | '/v4/summary'
    | '/deck'
    | '/v3'
    | '/v4'
    | '/api/v3/chat'
    | '/api/v3/gemini-live-token'
    | '/api/v4/chat'
    | '/workspace/activity/$activityId'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/compare-plans'
    | '/deck'
    | '/find-doctors'
    | '/learn'
    | '/login'
    | '/my-plans'
    | '/plans'
    | '/understanding'
    | '/v1'
    | '/v2'
    | '/v3'
    | '/v4'
    | '/workspace'
    | '/api/chat'
    | '/api/tts'
    | '/api/voice-session'
    | '/deck/ai'
    | '/deck/live'
    | '/v3/intake'
    | '/v3/matches'
    | '/v3/next-step'
    | '/v3/priorities'
    | '/v3/summary'
    | '/v4/intake'
    | '/v4/matches'
    | '/v4/next-step'
    | '/v4/priorities'
    | '/v4/summary'
    | '/deck/'
    | '/v3/'
    | '/v4/'
    | '/api/v3/chat'
    | '/api/v3/gemini-live-token'
    | '/api/v4/chat'
    | '/workspace/activity/$activityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  ComparePlansRoute: typeof ComparePlansRoute
  DeckRoute: typeof DeckRouteWithChildren
  FindDoctorsRoute: typeof FindDoctorsRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  MyPlansRoute: typeof MyPlansRoute
  PlansRoute: typeof PlansRoute
  UnderstandingRoute: typeof UnderstandingRoute
  V1Route: typeof V1Route
  V2Route: typeof V2Route
  V3Route: typeof V3RouteWithChildren
  V4Route: typeof V4RouteWithChildren
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiVoiceSessionRoute: typeof ApiVoiceSessionRoute
  ApiV3ChatRoute: typeof ApiV3ChatRoute
  ApiV3GeminiLiveTokenRoute: typeof ApiV3GeminiLiveTokenRoute
  ApiV4ChatRoute: typeof ApiV4ChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v4': {
      id: '/v4'
      path: '/v4'
      fullPath: '/v4'
      preLoaderRoute: typeof V4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v3': {
      id: '/v3'
      path: '/v3'
      fullPath: '/v3'
      preLoaderRoute: typeof V3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2': {
      id: '/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1': {
      id: '/v1'
      path: '/v1'
      fullPath: '/v1'
      preLoaderRoute: typeof V1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/understanding': {
      id: '/understanding'
      path: '/understanding'
      fullPath: '/understanding'
      preLoaderRoute: typeof UnderstandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-plans': {
      id: '/my-plans'
      path: '/my-plans'
      fullPath: '/my-plans'
      preLoaderRoute: typeof MyPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-doctors': {
      id: '/find-doctors'
      path: '/find-doctors'
      fullPath: '/find-doctors'
      preLoaderRoute: typeof FindDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck': {
      id: '/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare-plans': {
      id: '/compare-plans'
      path: '/compare-plans'
      fullPath: '/compare-plans'
      preLoaderRoute: typeof ComparePlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v4/': {
      id: '/v4/'
      path: '/'
      fullPath: '/v4/'
      preLoaderRoute: typeof V4IndexRouteImport
      parentRoute: typeof V4Route
    }
    '/v3/': {
      id: '/v3/'
      path: '/'
      fullPath: '/v3/'
      preLoaderRoute: typeof V3IndexRouteImport
      parentRoute: typeof V3Route
    }
    '/deck/': {
      id: '/deck/'
      path: '/'
      fullPath: '/deck/'
      preLoaderRoute: typeof DeckIndexRouteImport
      parentRoute: typeof DeckRoute
    }
    '/v4/summary': {
      id: '/v4/summary'
      path: '/summary'
      fullPath: '/v4/summary'
      preLoaderRoute: typeof V4SummaryRouteImport
      parentRoute: typeof V4Route
    }
    '/v4/priorities': {
      id: '/v4/priorities'
      path: '/priorities'
      fullPath: '/v4/priorities'
      preLoaderRoute: typeof V4PrioritiesRouteImport
      parentRoute: typeof V4Route
    }
    '/v4/next-step': {
      id: '/v4/next-step'
      path: '/next-step'
      fullPath: '/v4/next-step'
      preLoaderRoute: typeof V4NextStepRouteImport
      parentRoute: typeof V4Route
    }
    '/v4/matches': {
      id: '/v4/matches'
      path: '/matches'
      fullPath: '/v4/matches'
      preLoaderRoute: typeof V4MatchesRouteImport
      parentRoute: typeof V4Route
    }
    '/v4/intake': {
      id: '/v4/intake'
      path: '/intake'
      fullPath: '/v4/intake'
      preLoaderRoute: typeof V4IntakeRouteImport
      parentRoute: typeof V4Route
    }
    '/v3/summary': {
      id: '/v3/summary'
      path: '/summary'
      fullPath: '/v3/summary'
      preLoaderRoute: typeof V3SummaryRouteImport
      parentRoute: typeof V3Route
    }
    '/v3/priorities': {
      id: '/v3/priorities'
      path: '/priorities'
      fullPath: '/v3/priorities'
      preLoaderRoute: typeof V3PrioritiesRouteImport
      parentRoute: typeof V3Route
    }
    '/v3/next-step': {
      id: '/v3/next-step'
      path: '/next-step'
      fullPath: '/v3/next-step'
      preLoaderRoute: typeof V3NextStepRouteImport
      parentRoute: typeof V3Route
    }
    '/v3/matches': {
      id: '/v3/matches'
      path: '/matches'
      fullPath: '/v3/matches'
      preLoaderRoute: typeof V3MatchesRouteImport
      parentRoute: typeof V3Route
    }
    '/v3/intake': {
      id: '/v3/intake'
      path: '/intake'
      fullPath: '/v3/intake'
      preLoaderRoute: typeof V3IntakeRouteImport
      parentRoute: typeof V3Route
    }
    '/deck/live': {
      id: '/deck/live'
      path: '/live'
      fullPath: '/deck/live'
      preLoaderRoute: typeof DeckLiveRouteImport
      parentRoute: typeof DeckRoute
    }
    '/deck/ai': {
      id: '/deck/ai'
      path: '/ai'
      fullPath: '/deck/ai'
      preLoaderRoute: typeof DeckAiRouteImport
      parentRoute: typeof DeckRoute
    }
    '/api/voice-session': {
      id: '/api/voice-session'
      path: '/api/voice-session'
      fullPath: '/api/voice-session'
      preLoaderRoute: typeof ApiVoiceSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/activity/$activityId': {
      id: '/workspace/activity/$activityId'
      path: '/activity/$activityId'
      fullPath: '/workspace/activity/$activityId'
      preLoaderRoute: typeof WorkspaceActivityActivityIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/api/v4/chat': {
      id: '/api/v4/chat'
      path: '/api/v4/chat'
      fullPath: '/api/v4/chat'
      preLoaderRoute: typeof ApiV4ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v3/gemini-live-token': {
      id: '/api/v3/gemini-live-token'
      path: '/api/v3/gemini-live-token'
      fullPath: '/api/v3/gemini-live-token'
      preLoaderRoute: typeof ApiV3GeminiLiveTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v3/chat': {
      id: '/api/v3/chat'
      path: '/api/v3/chat'
      fullPath: '/api/v3/chat'
      preLoaderRoute: typeof ApiV3ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DeckRouteChildren {
  DeckAiRoute: typeof DeckAiRoute
  DeckLiveRoute: typeof DeckLiveRoute
  DeckIndexRoute: typeof DeckIndexRoute
}

const DeckRouteChildren: DeckRouteChildren = {
  DeckAiRoute: DeckAiRoute,
  DeckLiveRoute: DeckLiveRoute,
  DeckIndexRoute: DeckIndexRoute,
}

const DeckRouteWithChildren = DeckRoute._addFileChildren(DeckRouteChildren)

interface V3RouteChildren {
  V3IntakeRoute: typeof V3IntakeRoute
  V3MatchesRoute: typeof V3MatchesRoute
  V3NextStepRoute: typeof V3NextStepRoute
  V3PrioritiesRoute: typeof V3PrioritiesRoute
  V3SummaryRoute: typeof V3SummaryRoute
  V3IndexRoute: typeof V3IndexRoute
}

const V3RouteChildren: V3RouteChildren = {
  V3IntakeRoute: V3IntakeRoute,
  V3MatchesRoute: V3MatchesRoute,
  V3NextStepRoute: V3NextStepRoute,
  V3PrioritiesRoute: V3PrioritiesRoute,
  V3SummaryRoute: V3SummaryRoute,
  V3IndexRoute: V3IndexRoute,
}

const V3RouteWithChildren = V3Route._addFileChildren(V3RouteChildren)

interface V4RouteChildren {
  V4IntakeRoute: typeof V4IntakeRoute
  V4MatchesRoute: typeof V4MatchesRoute
  V4NextStepRoute: typeof V4NextStepRoute
  V4PrioritiesRoute: typeof V4PrioritiesRoute
  V4SummaryRoute: typeof V4SummaryRoute
  V4IndexRoute: typeof V4IndexRoute
}

const V4RouteChildren: V4RouteChildren = {
  V4IntakeRoute: V4IntakeRoute,
  V4MatchesRoute: V4MatchesRoute,
  V4NextStepRoute: V4NextStepRoute,
  V4PrioritiesRoute: V4PrioritiesRoute,
  V4SummaryRoute: V4SummaryRoute,
  V4IndexRoute: V4IndexRoute,
}

const V4RouteWithChildren = V4Route._addFileChildren(V4RouteChildren)

interface WorkspaceRouteChildren {
  WorkspaceActivityActivityIdRoute: typeof WorkspaceActivityActivityIdRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceActivityActivityIdRoute: WorkspaceActivityActivityIdRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  ComparePlansRoute: ComparePlansRoute,
  DeckRoute: DeckRouteWithChildren,
  FindDoctorsRoute: FindDoctorsRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  MyPlansRoute: MyPlansRoute,
  PlansRoute: PlansRoute,
  UnderstandingRoute: UnderstandingRoute,
  V1Route: V1Route,
  V2Route: V2Route,
  V3Route: V3RouteWithChildren,
  V4Route: V4RouteWithChildren,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiVoiceSessionRoute: ApiVoiceSessionRoute,
  ApiV3ChatRoute: ApiV3ChatRoute,
  ApiV3GeminiLiveTokenRoute: ApiV3GeminiLiveTokenRoute,
  ApiV4ChatRoute: ApiV4ChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
