/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyPlansRouteImport } from './routes/my-plans'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as FindDoctorsRouteImport } from './routes/find-doctors'
import { Route as DeckRouteImport } from './routes/deck'
import { Route as ComparePlansRouteImport } from './routes/compare-plans'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVoiceSessionRouteImport } from './routes/api/voice-session'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const MyPlansRoute = MyPlansRouteImport.update({
  id: '/my-plans',
  path: '/my-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const FindDoctorsRoute = FindDoctorsRouteImport.update({
  id: '/find-doctors',
  path: '/find-doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckRoute = DeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparePlansRoute = ComparePlansRouteImport.update({
  id: '/compare-plans',
  path: '/compare-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceSessionRoute = ApiVoiceSessionRouteImport.update({
  id: '/api/voice-session',
  path: '/api/voice-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare-plans': typeof ComparePlansRoute
  '/deck': typeof DeckRoute
  '/find-doctors': typeof FindDoctorsRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/my-plans': typeof MyPlansRoute
  '/api/chat': typeof ApiChatRoute
  '/api/voice-session': typeof ApiVoiceSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare-plans': typeof ComparePlansRoute
  '/deck': typeof DeckRoute
  '/find-doctors': typeof FindDoctorsRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/my-plans': typeof MyPlansRoute
  '/api/chat': typeof ApiChatRoute
  '/api/voice-session': typeof ApiVoiceSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare-plans': typeof ComparePlansRoute
  '/deck': typeof DeckRoute
  '/find-doctors': typeof FindDoctorsRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/my-plans': typeof MyPlansRoute
  '/api/chat': typeof ApiChatRoute
  '/api/voice-session': typeof ApiVoiceSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare-plans'
    | '/deck'
    | '/find-doctors'
    | '/learn'
    | '/login'
    | '/my-plans'
    | '/api/chat'
    | '/api/voice-session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare-plans'
    | '/deck'
    | '/find-doctors'
    | '/learn'
    | '/login'
    | '/my-plans'
    | '/api/chat'
    | '/api/voice-session'
  id:
    | '__root__'
    | '/'
    | '/compare-plans'
    | '/deck'
    | '/find-doctors'
    | '/learn'
    | '/login'
    | '/my-plans'
    | '/api/chat'
    | '/api/voice-session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComparePlansRoute: typeof ComparePlansRoute
  DeckRoute: typeof DeckRoute
  FindDoctorsRoute: typeof FindDoctorsRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  MyPlansRoute: typeof MyPlansRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiVoiceSessionRoute: typeof ApiVoiceSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-plans': {
      id: '/my-plans'
      path: '/my-plans'
      fullPath: '/my-plans'
      preLoaderRoute: typeof MyPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-doctors': {
      id: '/find-doctors'
      path: '/find-doctors'
      fullPath: '/find-doctors'
      preLoaderRoute: typeof FindDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck': {
      id: '/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare-plans': {
      id: '/compare-plans'
      path: '/compare-plans'
      fullPath: '/compare-plans'
      preLoaderRoute: typeof ComparePlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice-session': {
      id: '/api/voice-session'
      path: '/api/voice-session'
      fullPath: '/api/voice-session'
      preLoaderRoute: typeof ApiVoiceSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComparePlansRoute: ComparePlansRoute,
  DeckRoute: DeckRoute,
  FindDoctorsRoute: FindDoctorsRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  MyPlansRoute: MyPlansRoute,
  ApiChatRoute: ApiChatRoute,
  ApiVoiceSessionRoute: ApiVoiceSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
